### ISSUE TITLE
Integer division

### ISSUE THREAD

**Issue by gysvanzyl** [Arris-Composites/ODB2VTK#16]
Running the code on a couple of my .odb files results in the following error output:

`Traceback (most recent call last):
  File "P:\Gys\ParaView\odb2vtk.py", line 706, in <module>
    odb2vtk.WriteVTUFiles()
  File "P:\Gys\ParaView\odb2vtk.py", line 432, in WriteVTUFiles
    self.WriteVTUFile([stepName, frameIdx])
  File "P:\Gys\ParaView\odb2vtk.py", line 488, in WriteVTUFile
    pBuffer, cBuffer = self.WriteFieldOutputData(
  File "P:\Gys\ParaView\odb2vtk.py", line 263, in WriteFieldOutputData
    self.WriteDataArrayWithSectionPoints(
  File "P:\Gys\ParaView\odb2vtk.py", line 291, in WriteDataArrayWithSectionPoints
    buffer += self.WriteDataArray(fldOutput, vtkData, fldName, dataType)
  File "P:\Gys\ParaView\odb2vtk.py", line 334, in WriteDataArray
    writer(subset.bulkDataBlocks, instanceName, dataArray)
  File "P:\Gys\ParaView\odb2vtk.py", line 364, in WriteSortedCellData
    cellDataArray[indices, 0 : column * n] = block.data.reshape(
TypeError: 'numpy.float64' object cannot be interpreted as an integer`

The error is resolved when line 364 in odb2vtk.py is changed from
`                cellDataArray[indices, 0 : column * n] = block.data.reshape(
                    row / n, column * n
`
to
`                cellDataArray[indices, 0 : column * n] = block.data.reshape(
                    row // n, column * n
`

**Comment by YangShen398** [comment]
Hi,

are you using Abaqus 2024 with python 3? DS finally upgraded from python 2 to 3. In python 3, the division operation /  of two integers returns a float by default instead of an integer, as in python 2. So I believe this is why you encounter such an issue. Thanks for pointing it out. There may be more changes due to the change of python version. If you spot any other problems, let me know. Thanks. 

Yang

**Comment by YangShen398** [comment]
fixed by #17
